# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - achievers-admin

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: duvet86/achievers-app:latest

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      # - name: 🔓 Azure authentication
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # client-id: ${{ secrets.AZURE_CLIENT_ID }}
      # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: 🚀 Deploy to Azure WebApp (production)
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: "achievers-admin"
      #     images: duvet86/achievers-app:latest
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "achievers-admin"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6B0EB860F87540C18BBBD61BAF884202 }}
          images: duvet86/achievers-app:latest
